# Generated by Django 4.1.5 on 2023-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi_tricote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default=2874754334960, upload_to='images/'),
            preserve_default=False,
        ),
    ]
